#!/usr/bin/bash

if [ $# -gt 1 ]; then
	echo "Too many arguments!";
	echo "No arguments for all scripts or a keyword to narrow down results"
elif [ $# -eq 1 ]; then
	locate "*.nse" | sed 's/\.[^.]*$//' | rev | cut -d "/" -f 1 | rev | grep $1;
else
	locate "*.nse" | sed 's/\.[^.]*$//' | rev | cut -d "/" -f 1 | rev;
fi


